### ISSUE TITLE
ESYS: Align tcti loading with tpm2-tools and tabrmd

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1040] opened 2018-06-05 15:59 UTC
Use the same behavior for loading tcti libraries and library names as the tpm2-tools and the tabrmd.

**Comment by tstruk** [comment] 2018-07-03 23:40
This is duplicate of https://github.com/tpm2-software/tpm2-tss/issues/1046

**Closed** 2018-07-03 23:40 UTC
Labels: enhancement
