### ISSUE TITLE
NetBSD / Cirrus-CI data corruption ?

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1841] opened 2020-09-04 10:45 UTC
There's something strange happening on Cirrus-CI.
See https://cirrus-ci.com/task/5366219555471360?command=main#L1880

It seems like the tpm_server's answer is corrupted. No idea where this comes from and I have no means to trace it down.
Anyone with a NetBSD install who could investigate this ?

**Comment by williamcroberts** [comment] 2020-09-04 16:35
Virtual Machine?

**Comment by tstruk** [comment] 2020-09-04 17:08
If this could be reproduced locally then we could use wireshark tpm2 dissector to see how the response looks like.

**Comment by tstruk** [comment] 2021-03-05 21:50
This particular issue didn't happen for a while. Cirrus has it's problems, but now it is sufficient to re-trigger the build to fix it so closing the issue.

**Closed** 2021-03-05 21:50 UTC
Labels: project management
