### ISSUE TITLE
Make fails: missing failure

### ISSUE THREAD

**Issue by miraelim** [tpm2-software/tpm2-tss#1212] opened 2018-11-21 14:12 UTC
when I make after ./configure, the make is failed
logs are like that :
Makefile:13730: *** missing separator.  Stop.

**Comment by AndreasFuchsSIT** [comment] 2018-12-28 22:54
I'll close this since we got no feedback since november and doc has been updated.
If this is still an issue, please just reopen...

**Comment by leeehui** [comment] 2019-01-08 09:03
FYI
I use Ubuntu 16.04 LTS,  do NOT use version 2019.01.06

**Comment by diabonas** [comment] 2019-01-08 09:16
@leeehui Yes, unfortunately autoconf-archive 2019.01.06 has a backwards-incompatible change in `ax_code_coverage.m4`, see the [changelog](https://github.com/autoconf-archive/autoconf-archive/blob/master/NEWS#noteworthy-changes-in-release-20190106-2019-01-06-stable). For now, either stick to 2018.03.13 or apply the patch to `Makefile.am` in #1238 before using 2019.01.06.

**Comment by tonyespy** [comment] 2019-03-20 22:15
I can confirm this on Ubuntu xenial (16.04), as the latest available version of autoconf-archive from the Ubuntu archive is 20150925-1. This means the 2.2.x series of tss can't be built on 16.04 without installing autoconf-archive 20170928-2 from bionic or cosmic, or grabbing it from upstream git.

Any chance someone could add a notice about this breaking change to INSTALL.md in the section on Ubuntu?

**Comment by diabonas** [comment] 2019-03-21 10:12
IMHO this is already sufficiently documented in [INSTALL.md](https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md#gnulinux), which documents the minimum necessary version

> * GNU Autoconf Archive, version >= 2017.03.21

and states in the Ubuntu section:

> Note: In some Ubuntu versions, the lcov and autoconf-archive packages are incompatible with each other. It is recommended to download autoconf-archive directly from upstream and copy `ax_code_coverage.m4` and `ax_prog_doxygen.m4` to the `m4/` subdirectory of your tpm2-tss directory.

Furthermore, the problem concerns only building directly from the [`2.2.x` branch](https://github.com/tpm2-software/tpm2-tss/tree/2.2.x), the distribution tarballs like [`tpm2-tss-2.2.1.tar.gz`](https://github.com/tpm2-software/tpm2-tss/releases/download/2.2.1/tpm2-tss-2.2.1.tar.gz) already contain the necessary Autoconf Archive files and are therefore unaffected.

**Comment by tonyespy** [comment] 2019-03-21 21:41
> IMHO this is already sufficiently documented in [INSTALL.md](https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md#gnulinux), which documents the minimum necessary version
> 
> > * GNU Autoconf Archive, version >= 2017.03.21
> 
> and states in the Ubuntu section:
> 
> > Note: In some Ubuntu versions, the lcov and autoconf-archive packages are incompatible with each other. It is recommended to download autoconf-archive directly from upstream and copy `ax_code_coverage.m4` and `ax_prog_doxygen.m4` to the `m4/` subdirectory of your tpm2-tss directory.

Well, it wasn't super clear... as myself and two other co-workers missed it.

As you noted all versions thru 2.1.x build just fine on 16.04, which is why I thought calling out that release specifically (as it's an LTS release) would be helpful. Anyways it was just a suggestion. Thanks for your reply!

**Closed** 2019-03-22 14:29 UTC
