### ISSUE TITLE
Help: NV index with PCR policy 

### ISSUE THREAD

**Issue by lenardteri** [tpm2-software/tpm2-tss#1737] opened 2020-05-28 13:52 UTC
Hello, currently I am trying to bind a PCR policy to a NV index using the TSS2 FAPI, the NV index is created successfully with the json policy but after, the NV write operation fails trowing the error below. 

PCR current value: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

Policy json:
```
{
    "description":"Description pol_8_0",
    "policy":[
        {
            "type":"POLICYPCR",
            "pcrs":[
                {
                    "pcr":8,
                    "hashAlg":"TPM2_ALG_SHA1",
                    "digest":"0000000000000000000000000000000000000000"
                }
            ]
        }
    ]
}
```
From the FAPI profile:
```
 "pcr_selection": [
        { "hash": "TPM2_ALG_SHA1",
          "pcrSelect": [ 1, 8 ]
        },
        { "hash": "TPM2_ALG_SHA256",
          "pcrSelect": [ 9 , 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
        }
    ],
```

Error:

WARNING:esys:src/tss2-esys/api/Esys_PolicyPCR.c:288:Esys_PolicyPCR_Finish() Received TPM Error
ERROR:fapi:src/tss2-fapi/ifapi_policy_execute.c:217:execute_policy_pcr() ErrorCode (0x000002c4) Execute PolicyPCR_Finish.
ERROR:fapi:src/tss2-fapi/ifapi_policy_execute.c:1412:execute_policy_element() ErrorCode (0x000002c4) Execute policy pcr
ERROR:fapi:src/tss2-fapi/ifapi_policy_execute.c:1644:ifapi_policyeval_execute() Execute policy. ErrorCode (0x000002c4)
ERROR:fapi:src/tss2-fapi/ifapi_policyutil_execute.c:312:ifapi_policyutil_execute() Execute policy. ErrorCode (0x000002c4)
WARNING:esys:src/tss2-esys/api/Esys_FlushContext.c:234:Esys_FlushContext_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:89:Esys_FlushContext() Esys Finish ErrorCode (0x000001c4)
ERROR:fapi:src/tss2-fapi/fapi_util.c:1818:ifapi_authorize_object() Execute policy. ErrorCode (0x000002c4)
ERROR:fapi:src/tss2-fapi/fapi_util.c:1980:ifapi_nv_write() ErrorCode (0x000002c4) Authorize NV object.
ERROR:fapi:src/tss2-fapi/api/Fapi_NvWrite.c:261:Fapi_NvWrite_Finish() ErrorCode (0x000002c4)  FAPI NV Write
ERROR:fapi:src/tss2-fapi/api/Fapi_NvWrite.c:111:Fapi_NvWrite() ErrorCode (0x000002c4) NV_Write

What I am doing:

Create FAPI Context
Read json policy
Call FAPI_Import on json policy
Create NV Index with nvType="0x01C40001,noda" and the json policy
Try to write to Nv Index
Error occurs

**Comment by lenardteri** [comment] 2020-05-29 07:14
After a brief discussion with a colleague, is it possible that what I am trying to do in this scenario to not be possible at FAPI level? But only on lower API levels, such as ESYS or SYS APIs?

**Comment by JuergenReppSIT** [comment] 2020-05-29 07:25
I could reproduce your error and I'm currently preparing a PR. The problem was that a pcr selection size < 3 was computed. So it will be possible in FAPI. Until the PR is merged you could perhaps use PCR 16 for testing. Sorry for inconvenience

**Comment by lenardteri** [comment] 2020-05-29 07:27
It is not a urgent issue, don't worry. Thank you very much for the response!

**Comment by lenardteri** [comment] 2020-05-29 07:29
Using the PCR with index 16 works fine. Thanks again!

**Closed** 2020-06-01 23:47 UTC
