### ISSUE TITLE
EK certificate regression in 3.2.1

### ISSUE THREAD

**Issue by nullr0ute** [tpm2-software/tpm2-tss#2537] opened 2023-01-06 09:06 UTC
There's a regression in Fedora when we upgraded from tpm2-tss 3.2.0 -> 3.2.1 with EK certs:

````
# tpm2_getekcertificate -o ek_ecc.crt
ERROR:esys:src/tss2-esys/esys_iutil.c:1096:esys_GetResourceObject() Error: Esys handle does not exist (70018). 
ERROR: Esys_SequenceComplete(0x70018) - esapi:The ESYS_TR resource object is bad
ERROR: Failed to get shandle
ERROR: Failed to read NVRAM area at index 0x1C00002
````

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2158598

Both 3.2.0 and 4.0.0 appear to work OK.

**Comment by JuergenReppSIT** [comment] 2023-01-11 14:29
@nullr0ute I could not reproduce this error with tss 3.2.1 and tools 5.4 on rapian and ubuntu.
Would it be possible for you to create a trace for the command:
`TSS2_LOG=all+trace  tpm2_getekcertificate -o ek_ecc.crt > trace 2>&1`
and check the current version of the tools with:
`tpm2_getekcertificate -v`

**Comment by kkaarreell** [comment] 2023-01-19 14:37
@JuergenReppSIT Please see the trace attached to https://bugzilla.redhat.com/show_bug.cgi?id=2158598

**Comment by JuergenReppSIT** [comment] 2023-01-20 12:09
@kkaarreell Thank you for the trace and the tool version which causes the problem .With tpm2-tools 5.2 I could also reproduce the error .
The problem was caused by the fix: https://github.com/tpm2-software/tpm2-tss/commit/9239184a2236c9e4334c9374b86a2f632f4d8d7f
The tools did use an handle which was already by the tools. With older tss versions this did not cause problems because a duplicate was freed. From tpm2-tool version 5.3 this problem should be fixed.

**Comment by nullr0ute** [comment] 2023-01-20 12:43
We have tpm2-tools 5.4

**Comment by kkaarreell** [comment] 2023-01-20 15:09
I guess that was my bad judgement. We have encountered many test failures in keylime test suite on F36 and 3 test failures on F37 with the rust keylime agent. Both were passing when tpm2-tss was downgraded. I didn't investigate deeply whether there could be two distinct issues present and unfortunately did not try the simplified reproducer provided in the bug report (that works only F36, I can confirm). I will ask keylime devs for assistance with debugging the issue with the rust agent and report a new issue if it turns out to be a problem on tpm2-tss side.
I am sorry for the confusion.

**Comment by ansasaki** [comment] 2023-01-27 12:46
This bug affects not only `tpm2-tss 3.2.1` but also version `4.0.1`. A workaround on `tpm2-tools` is not enough as this also affects, for example, the rust wrapper `rust-tss-esapi`. See https://github.com/parallaxsecond/rust-tss-esapi/issues/383.

**Comment by JuergenReppSIT** [comment] 2023-01-27 13:54
@ansasaki yes the problem seems to be that  the rust esapi wrapper calls Esys_TR_FromTPMPublic twice and the function returns the same esys handle if the object already exists. It looks like the rust wrapper treats this as an error. This was introduced after fixing the HMAC problem of this function (commit https://github.com/tpm2-software/tpm2-tss/commit/9239184a2236c9e4334c9374b86a2f632f4d8d7f).
@AndreasFuchsTPM Should this be fixed for 4.0.1 and 3.2.1 to achieve again the behaviour that always a new esys object is created?

**Comment by williamcroberts** [comment] 2023-01-30 15:25
ESYS_TR handles can be the same, this seems like a bug in the bindings, they shouldn't be looking at them for uniqueness.

**Comment by JuergenReppSIT** [comment] 2023-01-30 15:49
> ESYS_TR handles can be the same, this seems like a bug in the bindings, they shouldn't be looking at them for uniqueness.

yes I would agree. It makes no sense to expect uniqueness in `tr_from_tpm_public`

**Comment by Superhepper** [comment] 2023-01-31 11:37
I think it was because the specification says something along the lines "Handle that references the object being created" that I incorrectly assumed it to be unique but we will fix that.

**Closed** 2023-05-26 06:27 UTC
