### ISSUE TITLE
No generated tpmclient execute after make command in tpm2-tss

### ISSUE THREAD

**Issue by duongthang009** [tpm2-software/tpm2-tss#784] opened 2018-02-26 07:57 UTC
In old version tpm2-tss, I can see generated tpmclient execute after make command in tpm2-tss.
But in current, no generated tpmclient execute. So, I can not run $./tpmclient for testing.
Please suggest for me. Thanks

**Comment by martinezjavier** [comment] 2018-02-26 08:56
@duongthang009 it's part of the test harness now and only built if you enable `--enable-unit` configure option and pass the simulator to `--with-simulatorbin`, for example:

```
$ ./configure --enable-unit --with-simulatorbin=/foo/bar/tpm_server

    tpm2-tss 2.0.0-dev       
    esapi:              yes  
    tctidefaultmodule:  Socket                             
    tctidefaultconfig:  tcp://127.0.0.1:2321               
    unit:               yes  
    debug:              no   
    simulatorbin:       /foo/bar/tpm_server                                                      
    loglevel:           trace                              
    doxygen:            1

$ make check

$ ./test/tpmclient/tpmclient.int
```

**Comment by dinhthienkhai** [comment] 2018-02-26 09:39
I also had that issue like duongthang009. 
And I followed your step, martinezjavier. But it still doesn't generate tpmclient.int file, it just is tpmclient.int.c
So can't handle on that file.
Can you show me more detail to gen tpmclient execute file.
Tks!

**Comment by duongthang009** [comment] 2018-02-26 09:41
I built tpm_server and save in /home/thangdt/WorkSpace/tpm2-server/src/tpm_server.
And run command as the follow:
$./tpm2-server/src/tpm_server
$./configure --enable-unit --with-simulatorbin=/home/thangdt/WorkSpace/tpm2-server/src/tpm_server
$make
But, there is no tpmclient.int execution in test/tpmclient.

**Comment by martinezjavier** [comment] 2018-02-26 10:03
@duongthang009 @dinhthienkhai please read my example, you have to execute `make check` for it to be build.

**Comment by duongthang009** [comment] 2018-02-26 10:20
Hi martinezjavier,
Please check my commands as the picture below.
![tpm_tss](https://user-images.githubusercontent.com/20437521/36665040-0618fc3a-1b19-11e8-89e6-73e4c5f0771a.png)
Thanks

**Comment by martinezjavier** [comment] 2018-02-26 10:50
Can you share your configure command?

I don't think you need to manually start the tpm_server to build tpmclient.int and run the test harness (I don't have access to a machine to check now though).

**Comment by duongthang009** [comment] 2018-02-26 11:00
Please see my configure file in the attach.
$./configure --enable-unit --with-simulatorbin=/home/thangdt/WorkSpace/tpm2-server/src/tpm_server

[configure.txt](https://github.com/tpm2-software/tpm2-tss/files/1758245/configure.txt)
[configure_command.txt](https://github.com/tpm2-software/tpm2-tss/files/1758246/configure_command.txt)

**Comment by martinezjavier** [comment] 2018-02-26 11:09
@duongthang009 it seems the problem is that you have a very old cmoka version:

```
checking for CMOCKA... no
configure: error: Package requirements (cmocka >= 1.0) were not met:

Requested 'cmocka >= 1.0' but version of cmocka is 0.3.2
```

**Comment by duongthang009** [comment] 2018-02-26 11:34
I followed install instruction:
$ sudo apt -y install \
  autoconf-archive \
  libcmocka0 \
  libcmocka-dev \...
And I got result "libcmocka-dev is already the newest version. libcmocka0 is already the newest version"
I'm using ubuntu 14.04.
please let me know how can I fix this error.
Thanks

**Comment by martinezjavier** [comment] 2018-02-26 11:51
@flihp should we mention in the INSTALL doc the minimum release for each distro that are needed in order to build the project? Although this is only when building the tests...

@duongthang009 why do you need the tpmclient out of interest? What's your goal?

**Comment by duongthang009** [comment] 2018-02-26 12:24
Hi martinezjavier,
I want to test HMAC and policy in Edk2, but I not found the function that the same ComputeCommandHmacs in tpm lib of Edk2.
So, I tried to run ComputeCommandHmacs function in tpm2-tss.
Please support for me if you know about it.
Thank you so much for your support.

**Comment by martinezjavier** [comment] 2018-02-26 12:27
@duongthang009 I see, so you should either install cmocka from source or create a container with a newer distro than your Ubuntu 14.04 LTS if you want to install them from packages.

**Comment by tstruk** [comment] 2018-02-26 18:42
@martinezjavier The unit tests and integ tests can be enabled separately. @duongthang009 if you only need integ test (and the tpmclient), then don't need to enable the unit tests. Just do:
./configure ---with-simulatorbin=<PATH_TO_SIM>/src/tpm_server
and then make check.
This way you should be able to build tpmclient without upgrading cmoka.

**Comment by martinezjavier** [comment] 2018-02-26 18:46
@tstruk oh, great. I didn't know that. Probably we should make it more clear in the INSTALL doc.

**Comment by tstruk** [comment] 2018-02-26 19:01
@martinezjavier sure, I will update the INSTALL doc.

**Comment by dinhthienkhai** [comment] 2018-02-27 02:02
@martinezjavier @tstruk, Hope you update soon.
Thank you.

**Comment by duongthang009** [comment] 2018-02-27 07:43
@martinezjavier  thank you very much for your support.
@tstruk . I ran the command "./configure ---with-simulatorbin=<PATH_TO_SIM>/src/tpm_server", "make check". Then I got tpmclient.int execution and ran it. But I got the warning and error as attached file.
I expected, I can get logged information for functions testing in tpmclient.int
Thanks
[MakeCheck_TpmClient.txt](https://github.com/tpm2-software/tpm2-tss/files/1761684/MakeCheck_TpmClient.txt)

**Comment by flihp** [comment] 2018-02-27 15:18
@martinezjavier no objections to putting version data in the INSTALL file, but it may be best to make these hard failures in the configure script. If configure is passed `--enable-unit` and the version requirements aren't met then we should probably throw an error and halt the configure script. I'm surprised it doesn't do this already.

**Comment by martinezjavier** [comment] 2018-02-27 15:50
@flihp yes, you are right.

**Comment by flihp** [comment] 2018-02-27 15:58
see #789

**Comment by tstruk** [comment] 2018-02-27 15:59
@duongthang009 These warnings are expected because the tpmclient performs some invalid cases as well. To see more detailed info of what it runs you can increase the verbosity by:
export TSS2_LOG=all+ERROR,testtpmclient+TRACE and then rerun the tpmclient.int.
It should report all tests it is running and the result of each.

**Comment by flihp** [comment] 2018-03-01 15:00
Seems like this one is sorted? Closing but please re-open if necessary.

**Closed by flihp** 2018-03-01 15:00 UTC
